### ISSUE TITLE
The embeded toot is gone

### ISSUE THREAD

**Issue by badboy** [chamook/thatsoundslikealotof.work#1]
> https://toots.chamook.lol/@chamook/109397401160074020

Oh noes! The server seems to be gone (or moved fully to social.chamook.lol?)
Anyway, there's no more content on thatsoundslikealotof.work  :(

But I guess fixing all of that sounds like a lot of work.

(Thanks for doing this tiny little site, it always put a smile on my face whenever I referenced it in some chats).

**Comment by chamook** [comment]
I'm (happily) surprised that anyone ever visited this silly website I made 😀 

I migrated to social.chamook.lol but I did not know of a way to preserve the toots across the transfer. 

Maybe I should just update it with a link to this issue 😅

**Comment by chamook** [comment]
I have pushed an update, thank you for raising the issue, I hope that the site still makes you smile :)
